### ISSUE TITLE
Build app test

### ISSUE THREAD

**Issue by movewho** [SamsungDForum/Preview#1]
Hi, 
I get config.xml from sample anh put it on my app. I run test on Samsung Tizen (UA43KU5500) but i don't see preview image? Please help me. 
This is my config.xml

[config.txt](https://github.com/SamsungDForum/Preview/files/365598/config.txt)

**Comment by ghost** [comment]
Hello, this is Sue.
First, Thank you for your concern.

I think your config.xml has no problem.

And did you test Preview sample application, [previewSampleApp.wgt file] on Github ?
Please test the sample app.
And then if it doesn't work, maybe your TV is somthing wrong,
if it works well, maybe your application has some problem.

After checking, and please send TV  firmware information or your application code.

**Comment by movewho** [comment]
Hi Sue,

I don't have test previewSampleApp.wgt  . How to test it from IDE?
On my tv, I see Youtube apps , NetFlix show preview image good.

About my TV:
- Model Code : UA43KU5500
- Software Version: T-HKMFKUABC-1113.0

Thanks.

**Comment by ghost** [comment]
You can import this sample app to IDE and check it on Emulator.
1. On this site, install SDK
   https://www.samsungdforum.com/TizenDevtools/SdkDownload
2. Import previewSampleApp.wgt on IDE
3. Launch Emulator
4.  Run the sample app

Please check.

**Comment by movewho** [comment]
Hi, 

I'm try to import to IDE, but I can run app :(. 
Can you take a photo about how to run the sample app?

Thanks

**Comment by ghost** [comment]
Please refer to the URL.
1. Import previewSampleApp.wgt on IDE
   https://www.samsungdforum.com/TizenGuide/tizen4901/index.html
2. Launch Emulator / 4. Run the sample app
   https://www.samsungdforum.com/TizenGuide/tizen2911/index.html

**Comment by movewho** [comment]
Hi, Sue

I add this line config.xml and myapp work on tv. That's is strange :(

`<tizen:metadata key="http://samsung.com/tv/metadata/use.accelerator" value="endpoint_URL=https://www.samsungdforum.com/Preview/sampleJSON.json"/>`

Thanks for your support :)

**Comment by ghost** [comment]
OK I see. Sorry to late.

Your TV firmware maybe litte old. So use.preview tag doesn't work.
You can check Lastest firmware version in TV setting menu.

Although TV firmware is updated, you can both use use.accelerator and use.preview tag.
But use.accelerator tag maybe not work on TV 2017 model.
Please check it.

**Comment by movewho** [comment]
If I  use **use.accelerator** and **use.preview** tag in config.xml file, are there a problems?

`<tizen:metadata key="http://samsung.com/tv/metadata/use.accelerator" value="endpoint_URL=https://www.samsungdforum.com/Preview/sampleJSON.json"/>
<tizen:metadata key="http://samsung.com/tv/metadata/use.preview" value="endpoint_URL=https://www.samsungdforum.com/Preview/sampleJSON.json"/>`

**Comment by ghost** [comment]
Maybe.. I think it is no problem.
But I recommend.. use only use.preview tag after upgrading firmware. ^_^

**Comment by movewho** [comment]
I'm afraid if the user's Smart Tizen TV isn't update to new firmware , my application will not work, so I use both **use.accelerator** and **use.preview** tag to support both the old and new firmware.
Thank you very much :+1:
